In [1]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
import csv

In [100]:
#csvを読み込む
def csv_to_array(file_name):
    csv_input = pd.read_csv("Data/length/"+file_name+".csv")
    data = np.round(np.array(csv_input.values)*50)*2
    data_max_value = 0
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            if math.isnan(data[i][j]):
                data[i][j] = 0
            if data[i][j] > data_max_value:
                data_max_value = data[i][j]
    #print(data_max_value)
    return (data, data_max_value)

def make_plot_data(data, data_max_value):
    plot_data = np.array([np.zeros((data.shape[1], int(data_max_value))) for i in range(data.shape[0])])
    for i in range(plot_data.shape[0]):
        for j in range(plot_data.shape[1]):
            for l in range(int((plot_data.shape[2] -data[i][j])/2), int((plot_data.shape[2]+data[i][j])/2)):
                plot_data[i][j][l] = 1
        plot_data[i] = plot_data[i][::-1]
    return plot_data

def conv_to_RGB(data):
    list = [[]for i in range(data.shape[0])]
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            if data[i][j] == 1:
                list[i].append([0.0,0.0,0.0])
            else:
                list[i].append([1.0,1.0,1.0])
    return list

def area(data):
    ret = np.zeros(data.shape[0])
    for i in range(data.shape[0]):
        ret[i] = np.sum(data[i])
    return ret

def write_area(file_name):
    data, data_max_value = csv_to_array(file_name)
    data_max_value = 50
    plot_data = make_plot_data(data, data_max_value)
    area_data = area(plot_data)
    f = open("Data/area.csv", "a")
    csvWriter = csv.writer(f, lineterminator="\n")
    csvWriter.writerow(area_data[:19])
    csvWriter.writerow(area_data[19:])
    f.close()

def max_width(data):
    ret = np.zeros(data.shape[0])
    for i in range(data.shape[0]):
        ret[i] = np.amax(data[i])
    return ret
    
def write_width(file_name):
    data, data_max_value = csv_to_array(file_name)
    width_data = max_width(data)
    f = open("Data/max_width.csv", "a")
    csvWriter = csv.writer(f, lineterminator="\n")
    csvWriter.writerow(width_data[:19])
    csvWriter.writerow(width_data[19:])
    f.close()

def max_height(data):
    ret = np.zeros(data.shape[0])
    for i in range(data.shape[0]):
        ret[i] = np.amax(np.sum(data[i], axis=0))*4
    return ret

def write_height(file_name):
    data, data_max_value = csv_to_array(file_name)
    data = make_plot_data(data, data_max_value)
    height_data = max_height(data)
    f = open("Data/max_height.csv", "a")
    csvWriter = csv.writer(f, lineterminator="\n")
    csvWriter.writerow(height_data[:19])
    csvWriter.writerow(height_data[19:])
    f.close()
    
def center(data):
    ret = np.zeros(data.shape[0])
    for i in range(data.shape[0]):
        w = np.diag(np.array([(2+4*i) for i in range(data.shape[1])]))
        ret[i] = np.sum(np.dot(w, data[i][::-1]))/np.sum(data[i])
    return ret

def write_center(file_name):
    data, data_max_value = csv_to_array(file_name)
    data = make_plot_data(data, data_max_value)
    center_data = center(data)
    f = open("Data/center.csv", "a")
    csvWriter = csv.writer(f, lineterminator="\n")
    csvWriter.writerow(center_data[:19])
    csvWriter.writerow(center_data[19:])
    f.close()

In [101]:
write_center("answer")
write_center("kameda")
write_center("yamamoto")
write_center("yoshino")
write_center("kobatake")
write_center("ichimura")
write_center("morita")
write_center("shimoyama")
write_center("matsunaga")
write_center("michizono")
write_center("nakagawa")

In [99]:
a = np.array([[1,1,1],[0,1,0]])
print(a)
b = np.diag(np.array([(2+4*i) for i in range(a.shape[0])]))
print(b)
print(np.dot(b,a))
print(np.sum(np.dot(b,a))/np.sum(a))

[[1 1 1]
 [0 1 0]]
[[2 0]
 [0 6]]
[[2 2 2]
 [0 6 0]]
3.0
